export const moviesData =[
    {
        id: 1,
        title: "LE SAMARITAIN",
        date: '2021-06-25',
        genre: ' Action, Adventure, Crime, Thriller',
        description: "Synopsis. Sam Cleary, âgé de 13 ans, vit avec sa mère Tiffany dans un immeuble malfamé de Granite City. Le jeune garçon est fan du Samaritain (Samaritan en VO ), un ancien super-héros mythique disparu il y a plus de vingt ans, à la suite d'une bataille contre son frère jumeau et ennemi, Nemesis.",
        posterURL: "https://fr.web.img5.acsta.net/pictures/22/07/28/10/38/3703654.jpg",
        rating: 5,
        trailer: "https://www.youtube.com/embed/vMqqSVFgTSg",
      },
      { id:2,
        title: "Viking Wolf",
        date: "2021-09-08",
        genre: "Science Fiction, Action, Thriller",
        description: "La jeune Thale vient juste de déménager avec ses deux parents dans une petite ville, après que sa mère a trouvé un nouveau boulot dans la police locale.",
        posterURL: "https://resizing.flixster.com/KjIKqZnj2-5bQJRuujpTYGaolmk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzBjNzRjYTMwLTc5ZWMtNDZiNS04MjAzLTJiNjkzYjg3MTNjYS5qcGc=",
        rating: 4,
        trailer: "https://www.youtube.com/embed/6sxnOLRGkhw",
      },
      { id:3,
        title: "The Guilty",
        date: '2019-10-04',
        genre: ' Crime, Thriller, Drama',  
        description: "The Guilty is inspired by the 2018 film of the same name, directed by Gustav Moller. This 2021 adaptation has been written by Nic Pizzolatto and directed by Antoine Fuqua. ... The film takes you on a journey where you see a protagonist burdened by guilt, and everything he touches just breaks into fragments.",
        posterURL: "https://fr.web.img4.acsta.net/c_310_420/pictures/21/08/31/11/07/4346618.jpg",
        rating: 3,
        trailer: "https://www.youtube.com/embed/NaB_ERMAZu4",
      },
    ];